package com.staminal.venue.audit;

public enum AuditAction {
    ADMIN_USER_CREATED,
    ADMIN_USER_ROLE_CHANGED,
    ADMIN_USER_PASSWORD_RESET,
    ADMIN_USER_STATUS_CHANGED,
    HALL_APPROVED,
    HALL_REJECTED,
    VENDOR_APPROVED,
    VENDOR_REJECTED,
    REQUIREMENT_CREATED,
    REQUIREMENT_DISTRIBUTED,
    LEAD_STATUS_CHANGED,
    QUOTE_CREATED,
    QUOTE_UPDATED,
    BOOKING_CREATED,
    BOOKING_STATUS_CHANGED,
    REVIEW_CREATED,
    REVIEW_UPDATED,
    REVIEW_APPROVED,
    REVIEW_HIDDEN,
    AVAILABILITY_BLOCKED,
    AVAILABILITY_DELETED
}
