package com.staminal.venue.audit;

public enum AuditAction {
    ADMIN_USER_STATUS_CHANGED,
    HALL_APPROVED,
    HALL_REJECTED,
    VENDOR_APPROVED,
    VENDOR_REJECTED,
    LEAD_STATUS_CHANGED,
    BOOKING_CREATED,
    BOOKING_STATUS_CHANGED,
    REVIEW_CREATED,
    REVIEW_UPDATED,
    REVIEW_APPROVED,
    REVIEW_HIDDEN,
    AVAILABILITY_BLOCKED,
    AVAILABILITY_DELETED
}
